host: 127.0.0.1
port: 4020
baseurl: "/new-site"
permalink: pretty
sass:
    sass_dir: _sass
    style: :compressed
prose:
  ignore: [
    '*.*'
    ]
  siteurl: 'https://bmlp.org/static-starter/'
  relativeLinks: 'https://bmlp.org/static-starter/links.jsonp'
  media: 'media'
  metadata:
    _posts/faqs:
      - name: "category"
        field:
          element: "hidden"
          value: "faq"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "faqtype"
        field:
          element: "select"
          label: "FAQ Section"
          options:
            - name: Know Your Rights
              value: kyr
            - name: Legal Observation
              value: legal-observers
            - name: Jail Support
              value: jail-support
